---
title: "About Variables Chosen"
description: |
  Details of the variable choices from the WVS/EVS integrated data set and ISSP data set
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Variable Choice

## IVS Variables

The variables I am looking at:

### Country Identifiers and Weight

* Column 10: cntry (ISO-3 numeric Country Code)

* Column 35: wght_eq1000 (Equilibrated weight: Equilibrated weights are weighting factors whose goal is to transform the sample’s n to 1000 making all samples count the same in a combined analysis.)

### Importance Variables

#### Columns 41-46: A001 to A006 - How important each of the following is in your life:

* A001: Family
* A002: Friends
* A003: Leisure Time
* A004: Politics
* A005: Work
* A006: Religion

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very important
* 2: Rather important
* 3: Not very important
* 4: Not at all important

### Satisfaction Variables

#### Column 47: A008 (Feeling of happiness)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very happy
* 2: Quite happy
* 3: Not very happy
* 4: Not at all happy

#### Column 48: A009 (State of Health)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very good
* 2: Good
* 3: Fair
* 4: Poor
* 5: Very poor

#### Column 49: A170 (Satisfaction with your life)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* (1) Dissatisfied to (10) Satisfied

#### Column 50: A173 (Freedom of choice and control over life)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* (1) None at all to (10) A great deal

### Political/Civic Engagement Variables

#### Column 106: E012 (Willingness to fight for country. Would you be willing?)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: No
* 2: Yes

#### Column 109: E023 (Interest in politics)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very interested
* 2: Somewhat interested
* 3: Not very interested
* 4: Not at all interested

#### Column 110: E025 (Propensity to sign a petition)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Have done
* 2: Might do
* 3: Would never do

#### Column 111: E026 (Propensity to join boycotts)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Have done
* 2: Might do
* 3: Would never do

#### Column 112: E027 (Propensity to attend lawful/peaceful demonstrations)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Have done
* 2: Might do
* 3: Would never do

#### Column 113: E028 (Propensity to join unofficial strikes)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Have done
* 2: Might do
* 3: Would never do

#### Column 114: E033 (Self positioning in political scale)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* (1) Left to (10) Right

### Confidence in Institutions

#### Column 119: E069_01 (Confidence in Churches)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 120: E069_02 (Confidence in Armed Forces)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 121: E069_04 (Confidence in The Press)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 122: E069_05 (Confidence in Labour Unions)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 123: E069_06 (Confidence in The Police)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 124: E069_07 (Confidence in Parliament)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 125: E069_08 (Confidence in Civil Services)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 126: E069_18A (Confidence in Major Regional Organization)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

* Note:

Constructed variable combining the following country-specific major regional organizations used in the surveys as follows:
The European Union (EU): in all EVS5 countries and Andorra, Cyprus, Germany, Greece, Serbia, Romania, Turkey, Ukraine
The Asia-Pacific Economic Cooperation (APEC): in Japan, Malaysia, South Korea
The Arab League: in Egypt, Iraq, Jordan, Lebanon, Tunisia
The Association of South East Asian Nations (ASEAN): in Bangladesh, Indonesia, Myanmar, Philippines, Thailand, Vietnam The African Union (AU): in Ethiopia, Nigeria, Zimbabwe
Commonwealth of Independent States (CIS): in Kazakhstan, Kyrgyzstan, Russia, Tajikistan
Economic Cooperation Organization (ECO): in Iran
The Mercosur: in Argentina, Bolivia, Brasil, Colombia, Ecuador, Guatemala, Puerto Rico The Organization of American States (OAE): in Peru
The North American Free Trade Agreement (NAFTA): in USA
The South Asian Association for Regional Cooperation (SAARC): in Pakistan
The Shanghai Cooperation Organization (SCO): in Hong Kong SAR

#### Column 127: E069_18 (Confidence in EU)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

Data not available for: WVS7: All countries/territories besides Andorra, Taiwan ROC, Cyprus, Germany, Greece, Kyrgyzstan, Romania, Serbia, Tajikistan, Turkey, Ukraine

#### Column 128: E069_11 (Confidence in The Government)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 129: E069_12 (Confidence in Political Parties)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 130: E069_13 (Confidence in Major Companies)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 131: E069_14 (Confidence in Environmental Protection Movement)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 132: E069_17 (Confidence in Justice System/Courts)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 133: E069_20 (Confidence in The United Nations)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A great deal
* 2: Quite a lot
* 3: Not very much
* 4: None at all

#### Column 134: E111_01 (Satisfaction with the political system of their country)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* (1) Not satisfied at all to (10) Completely satisfied

#### Column 135-138: (Is this a good-bad way of governing this country?)

#### E114: Having a strong leader who does not have to bother with parliament and elections

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very good
* 2: Fairly good
* 3: Fairly bad
* 4: Very bad

#### E115: Having experts, not government, make decisions according to what they think is best for the country

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very good
* 2: Fairly good
* 3: Fairly bad
* 4: Very bad

#### E116: Having the army rule the country

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very good
* 2: Fairly good
* 3: Fairly bad
* 4: Very bad

#### E117: Is this a good-bad way of governing this country: Having a democratic political system

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very good
* 2: Fairly good
* 3: Fairly bad
* 4: Very bad

#### Column 150: E235 (How important is it for you to live in a country that is governed democratically?)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* (1) Not at all important to (10) Absolutely important

#### Column 151: E236 (How democratically is this country being governed today?)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* (1) Not at all democratic to (10) Completely democratic

#### Columns 152-161 (How often do these things occur in this country's elections?)

#### E263: (You vote in local elections?)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Always
* 2: Usually
* 3: Never
* 4: Not allowed to vote

#### E264 (You vote in national elections?)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Always
* 2: Usually
* 3: Never
* 4: Not allowed to vote

#### E265_01 (The votes are counted fairly in this country's elections?)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very often
* 2: Fairly often
* 3: Not often
* 4: Not at all often

#### E265_02 (Opposition candidates are prevented from running)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very often
* 2: Fairly often
* 3: Not often
* 4: Not at all often

#### E265_03 (TV news favors the governing party)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very often
* 2: Fairly often
* 3: Not often
* 4: Not at all often

#### E265_04 (Voters are bribed)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very often
* 2: Fairly often
* 3: Not often
* 4: Not at all often

#### E265_05 (Journalists provide fair coverage of elections)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very often
* 2: Fairly often
* 3: Not often
* 4: Not at all often

#### E265_06 (Election officials are fair)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very often
* 2: Fairly often
* 3: Not often
* 4: Not at all often

#### E265_07 (Rich people buy elections)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very often
* 2: Fairly often
* 3: Not often
* 4: Not at all often

#### E265_08 (Voters are threatened with violence at the polls)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very often
* 2: Fairly often
* 3: Not often
* 4: Not at all often

### Religious Variables

#### Column 162: F025 (Religious Denomination)

* 0: Missing, No Answer, Don't Know
* 1: Roman Catholic
* 2: Protestant
* 3: Orthodox (Russian/Greek/etc.)
* 4: Jew
* 5: Muslim
* 6: Hindu
* 7: Buddhist
* 8: Other Christian (Evangelical/Pentecostal/Free church/etc.)
* 9: Other
* 10: Do not belong to a denomination

#### Column 166: F034 (Overall would you say you are)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: A religious person
* 2: Not a religious person
* 3: A convinced atheist

### Closeness to Country/world

#### Columns 188-192: Closeness to country/world:  How close do you feel to...

#### G062 (the continent, e.g. Europe)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very close
* 2: Close
* 3: Not very close
* 4: Not close at all

#### G063 (the world)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very close
* 2: Close
* 3: Not very close
* 4: Not close at all

#### G255 (your town or city)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very close
* 2: Close
* 3: Not very close
* 4: Not close at all

#### G256 (your county, region, district)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very close
* 2: Close
* 3: Not very close
* 4: Not close at all

#### G257 (the country)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Very close
* 2: Close
* 3: Not very close
* 4: Not close at all

### Role of Government variables

#### Columns 193-195: Does this country's government have or should it have the right to the following:

#### H009 (keep people under video surveillance in public areas)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Definitely should have the right
* 2: Probably should have the right
* 3: Probably should not have the right
* 4: Definitely should not have the right

#### H010 (monitor all emails and any other information exchanged on the internet)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Definitely should have the right
* 2: Probably should have the right
* 3: Probably should not have the right
* 4: Definitely should not have the right

#### H011 (collect information about anyone living in the country without their knowledge)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Definitely should have the right
* 2: Probably should have the right
* 3: Probably should not have the right
* 4: Definitely should not have the right

### Demographic Variables

#### Column 196: X001 (Sex)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Male
* 2: Female

#### Columns 199: X003R (Recoded ages with intervals)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: 15-24
* 2: 25-34
* 3: 35-44
* 4: 45-54
* 5: 55-64
* 6: 65 and more years

#### Column 201: G027A (Born in or immigrant to country)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: I am born in this country
* 2: I am an immigrant to this country

#### Column 210: X007 (Marital Status)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Married
* 2: Living together as married
* 3: Divorced
* 4: Separated
* 5: Widowed
* 6: Single/Never married

#### Column 211: X011 (How many children in household)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: 1 child
* 2: 2 children
* 3: 3 children
* 4: 4 children
* 5: 5 children and more
* 6: No child

#### Column 212: x026_01 (Do you live with your parents)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: No
* 2: Yes, own parent(s)
* 3: Yes, parent(s) in law
* 4: Yes, both own parent(s) and parent(s) in law

#### Column 213: X013 (Number of people total in household including respondent)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: 1
* 2: 2
* 3: 3
* 4: 4
* 5: 5
* 6: 6 and more

#### Column 214: X025A_01 Highest Education Level Attained

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Less than primary
* 2: Primary
* 3: Lower secondary
* 4: Upper secondary
* 5: Post-secondary non tertiary
* 6: Short-cycle tertiary
* 7: Bachelor or equivalent
* 8: Master or equivalent
* 9: Doctoral or equivalent

#### Column 222: X028 (Employment Status of Respondent)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Full time (30h a week or more)
* 2: Part time (less then 30 hours a week)
* 3: Self employed
* 4: Retired/pensioned
* 5: Housewife (not otherwise employed)
* 6: Student
* 7: Unemployed
* 8: Other (Includes military service and disabled)

#### Column 224: X052 (Institution of occupation)

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: Public institution
* 2: Private business
* 3: Private non-profit organization

#### Columns 230-231: Income (Combined, variable "income")

* 0: Missing, Not Asked, Not Applicable, No Answer, Don't Know
* 1: 1st decile
* 2: 2nd decile
* 3: 3rd decile
* 4: 4th decile
* 5: 5th decile
* 6: 6th decile
* 7: 7th decile
* 8: 8th decile
* 9: 9th decile
* 10: 10th decile
