---
title: "Variable Choices"
author: "Kristina Becvar"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I want to look at:

Column 10: cntry (ISO-3 numeric Country Code)
Column 13: year
Column 31: lnge_num (Language of interview)
Column 33: gwght (Weight: These weights are meant to adjust some socio-demographic characteristics (age, sex, educational level and region of residence) in the sample population to the distribution of the target population.)
Column 34: pwght (Population size weight: Population size weights are provided for rescaling the weights to a common denominator across all countries. These weights must be applied whenever one ought to examining data for two or more countries combined and avoid the overrepresentation of small countries when compared to bigger ones.)
Column 35: wght_eq1000 (Equilibrated weight: Equilibrated weights are weighting factors whose goal is to transform the sample’s n to 1000 making all samples count the same in a combined analysis.)
COlumn 40: respint 
(Respondent interested during the interview
-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Very interested
2 Somewhat interested
3 Not very interested)

Columns 41-46: A001 to A006 - How important each of the following is in your life:

A001: Family
A002: Friends
A003: Leisure Time
A004: Politics
A005: Work
A006: Religion

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Very important
2 Rather important
3 Not very important
4 Not at all important)

Column 47: A008 (Feeling of happiness)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Very happy
2 Quite happy
3 Not very happy
4 Not at all happy)

Column 48: A009 (State of Health)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Very good
2 Good
3 Fair
4 Poor
5 Very poor)

Column 49: A170 (Satisfaction with your life)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Dissatisfied
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 Satisfied)

Column 50: A173 (Freedom of choice and control over life)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 None at all
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 A great deal)

Column 106: E012 (Willingness to fight for country. Would you be willing?)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
0 No
1 Yes)

Column 109: E023 (Interest in politics)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Very interested
2 Somewhat interested
3 Not very interested
4 Not at all interested)

Column 110: E025 (Propensity to sign a petition)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Have done
2 Might do
3 Would never do)

Column 111: E026 (Propensity to join boycotts)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Have done
2 Might do
3 Would never do)

Column 112: E027 (Propensity to attend lawful/peaceful demonstrations)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Have done
2 Might do
3 Would never do)

Column 113: E028 (Propensity to join unofficial strikes)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Have done
2 Might do
3 Would never do)

Column 114: E033 (Self positioning in political scale)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Lek
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 Right)

Column 119: E069_01 (Confidence in Churches)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 120: E069_02 (Confidence in Armed Forces)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 121: E069_04 (Confidence in The Press)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 122: E069_05 (Confidence in Labour Unions)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 123: E069_06 (Confidence in The Police)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 124: E069_07 (Confidence in Parliament)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 125: E069_08 (Confidence in Civil Services)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 126: E069_18A (Confidence in Major Regional Organization)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Note:
Constructed variable combining the following country-specific major regional organizations used in the surveys as follows:
The European Union (EU): in all EVS5 countries and Andorra, Cyprus, Germany, Greece, Serbia, Romania, Turkey, Ukraine
The Asia-Pacific Economic Cooperation (APEC): in Japan, Malaysia, South Korea
The Arab League: in Egypt, Iraq, Jordan, Lebanon, Tunisia
The Association of South East Asian Nations (ASEAN): in Bangladesh, Indonesia, Myanmar, Philippines, Thailand, Vietnam The African Union (AU): in Ethiopia, Nigeria, Zimbabwe
Commonwealth of Independent States (CIS): in Kazakhstan, Kyrgyzstan, Russia, Tajikistan
Economic Cooperation Organization (ECO): in Iran
The Mercosur: in Argentina, Bolivia, Brasil, Colombia, Ecuador, Guatemala, Puerto Rico The Organization of American States (OAE): in Peru
The North American Free Trade Agreement (NAFTA): in USA
The South Asian Association for Regional Cooperation (SAARC): in Pakistan
The Shanghai Cooperation Organization (SCO): in Hong Kong SAR

Column 127: E069_18 (Confidence in EU)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Data not available for:
WVS7: All countries/territories besides Andorra, Taiwan ROC, Cyprus, Germany, Greece, Kyrgyzstan, Romania, Serbia, Tajikistan, Turkey, Ukraine

Column 128: E069_11 (Confidence in The Government)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 129: E069_12 (Confidence in Political Parties)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 130: E069_13 (Confidence in Major Companies)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 131: E069_13 (Confidence in Major Companies)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 132: E069_14 (Confidence in Environmental Protection Movement)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 133: E069_17 (Confidence in Justice System/Courts)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 134: E069_20 (Confidence in The United Nations)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 A great deal
2 Quite a lot
3 Not very much
4 None at all)

Column 134: E111_01 (Satisfaction with the political system of their country)

(-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Not satisfied at all
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 Completely satisfied)

Column 135: E114 (Is this a good-bad way of governing this country: Having a strong leader who does not have to bother with parliament and elections)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Very good
2 Fairly good
3 Fairly bad
4 Very bad

Column 136: E115 (Is this a good-bad way of governing this country: Having experts, not government, make decisions according to what they think is best for the country)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Very good
2 Fairly good
3 Fairly bad
4 Very bad

Column 137: E116 (Is this a good-bad way of governing this country: Having the army rule the country)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Very good
2 Fairly good
3 Fairly bad
4 Very bad

Column 138: E117 (Is this a good-bad way of governing this country: Having a democratic political system)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Very good
2 Fairly good
3 Fairly bad
4 Very bad

Column 143: E226 (Is this an essential characteristic of a democracy: People choose their leaders in free elections.)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
0 It is against democracy (spontaneous)
1 Not an essential characteristic of democracy
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 An essential characteristic of democracy

Column 144: E227 (Is this an essential characteristic of a democracy: People receive state aid for unemployment.)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
0 It is against democracy (spontaneous)
1 Not an essential characteristic of democracy
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 An essential characteristic of democracy

Column 145: E228 (Is this an essential characteristic of a democracy: The army takes over when government is incompetent.)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
0 It is against democracy (spontaneous)
1 Not an essential characteristic of democracy
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 An essential characteristic of democracy

Column 146: E229 (Is this an essential characteristic of a democracy: Civil rights protect people from state oppression.)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
0 It is against democracy (spontaneous)
1 Not an essential characteristic of democracy
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 An essential characteristic of democracy

Column 147: E233 (Is this an essential characteristic of a democracy: Women have the same rights as men.)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
0 It is against democracy (spontaneous)
1 Not an essential characteristic of democracy
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 An essential characteristic of democracy

Column 148: E233A (Is this an essential characteristic of a democracy: The state makes people’s incomes equal.)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
0 It is against democracy (spontaneous)
1 Not an essential characteristic of democracy
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 An essential characteristic of democracy

Column 149: E233B (Is this an essential characteristic of a democracy: People obey their rulers.)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
0 It is against democracy (spontaneous)
1 Not an essential characteristic of democracy
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 An essential characteristic of democracy

Column 150: E235 (How important is it for you to live in a country that is governed democratically?)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Not at all important
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 Absolutely important

Column 151: E236 (how democratically is this country being governed today?)

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 Not at all democratic
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 Completely democratic


Columns 152-161: Questions about voting

Columns 162-171: Religiosity

Columns 188-192: Closeness to country/world

Columns 193-195: Government Surveillance

Columns 196-198: Sex and Age

Columns 199-200: Recoded ages with intervals

Column 201: Born in or immigrant to country

-5 Missing: Other
-4 Not asked in survey
-3 Not applicable
-2 No answer
-1 Don´t know
1 I am born in this country
2 I am an immigrant to this country

Columns 210-213: Demographics
Columns 214-221: Education
Columns 222-229: Job
Columns 201-231: Income





